### PR TITLE
fix tag name regex match to allow hyphen

### PR DESCRIPTION
**Pull request by AndersMad**
bug: the `\.-_` is chars from dot to underscore.. new regex missing special chars as to specs but should be better

### CODE REVIEW

**Comment by rogalmic** [comment]
I can see pull req is now closed. Is this still an issue?

**Comment by rogalmic** [comment]
Lets see how it goes, the test build is now available at:
https://marketplace.visualstudio.com/items?itemName=rogalmic.vscode-xml-complete
at downloads@latest:
https://github.com/rogalmic/vscode-xml-complete/releases/tag/untagged-3d5a654e9e0e7894083d

**Comment by AndersMad** [comment]
yes, but the `+` needs to be a `*` - my bad - else autocomplete wont work for `<` (empty tag name)

**Comment by rogalmic** [comment]
No worries, i will fix that. Thanks for your help!

**Pull request merged**
